### PR TITLE
[Breaking] Fix effect middleware to support stream requests and multipl resolutions

### LINKED ISSUE #428: EffectMiddleware makes it impossible to resolve stream effects more than once
The trait defines the callback as taking the request handle by move, but the middleware needs to also keep it in order to resolve it again later on.

### PR DESCRIPTION
**Pull request by charypar**
Fixes #428, by adjusting the effect callback in middleware to take request handle by mutable borrow, instead of value.

### CODE REVIEW

File: crux_core/src/middleware/effect_handling.rs [hunk 1]
```diff
@@ -39,8 +39,8 @@ where
     fn try_process_effect_with(
         &self,
         effect: Effect,
-        resolve_callback: impl FnOnce(
-            RequestHandle<<Self::Op as Operation>::Output>,
+        resolve_callback: impl Fn(
```
Comment (StuartHarris) [inline crux_core/src/middleware/effect_handling.rs]: Can this be `impl FnMut`, which is less restrictive than `Fn`?

**Review by StuartHarris — CHANGES_REQUESTED** [review]
Looks great 😍. Just one question.

File: crux_core/src/middleware/effect_handling.rs (hunk 1 above)
Comment (charypar) [reply crux_core/src/middleware/effect_handling.rs]: Done! I think I will never remember which way the restrictiveness goes 😅

Comment (StuartHarris) [reply crux_core/src/middleware/effect_handling.rs]: IKR 😓

**Review by StuartHarris — APPROVED** [review]
❤️

File: crux_core/src/middleware/effect_handling.rs (hunk 1 above)
Comment (StuartHarris) [reply crux_core/src/middleware/effect_handling.rs]: This is how I think about it. `FnOnce` is the widest set, because it also includes closures that can only be called once because they move data out into their environment. `FnMut` is the next widest because it includes closures that mutate their environment. `Fn` only includes closures that don't move out or mutate. And finally `fn()` is the most restrictive because it's a single type.
